apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: build
on:
  workflow_call:
    inputs:
      artifactName:
        type: string
        required: true
      baseVersion:
        type: string
        required: true
      digest:
        type: string
        required: false
jobs:
  build:
    steps:
      - uses: cloudbees-io/register-build-artifact@v1
        name: Publish artifact
        with:
          name: "${{ inputs.artifactName }}"
          version: "${{inputs.baseVersion}}-${{cloudbees.version}}"
          url: "docker.io/MyApp/${{ inputs.artifactName }}:${{inputs.baseVersion}}-${{cloudbees.version}}"
          digest: "${{ inputs.digest }}"
