
apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: MyApp Deploy
on:
  workflow_call:
    inputs:
      artifactName:
        type: string
        required: true
      artifactVersion:
        type: string
        required: true
      environment:
        type: string
        required: true
jobs:
  deploy:
    environment: ${{ inputs.environment }}
    steps:
      - name: Inform system that an artifact version was deployed
        uses: cloudbees-io/register-deployed-artifact@v1 # return to v1 once Action released
        with:
          name: "${{ inputs.artifactName }}"
          version: "${{ inputs.artifactVersion }}"
          url: "docker.io/MyApp/${{ inputs.artifactName }}:${{ inputs.artifactVersion }}" # Remove this once Action updated
          #target-environment: "${{ inputs.environment }}"
